### PR TITLE
Support STARTTLS

### LINKED ISSUE #2: Enhancement: Add StartTLS support

### PR DESCRIPTION
**Pull request by acheong08**
Closes #2

### CODE REVIEW

**Comment by acheong08** [comment]
With STARTTLS enabled, only a single OK is received when testing `pipelining` (at least for mailhostbox) even though both are parsed

**Comment by hannob** [comment]
It appears the patch contains some unrelated changes. (It sets the from address to the to address - why?)

Also, I'm not sure I want to have the added complexity of starttls at all. You can usually test unauth'ed connections via port 25 and auth'ed via 465, and it's unlikely a server behaves differently over starttls on the line endings, so I don't see much benefit.

**Comment by acheong08** [comment]
> It appears the patch contains some unrelated changes

Yup sorry about that. I was testing some other stuff and forgot to remove

**Comment by acheong08** [comment]
> Also, I'm not sure I want to have the added complexity of starttls at all. You can usually test unauth'ed connections via port 25 and auth'ed via 465

I'm fine with that. There are some mail servers which don't support 25 and 465, only STARTTLS (I don't know why). I can just close this PR.

>  it's unlikely a server behaves differently over starttls on the line endings, so I don't see much benefit.

In the specific case of mailhostbox, it does indeed behave differently, causing an index error. I see you've already fixed it. Although I was receiving 2 emails, I only got 1 OK response.

**Pull request closed without merging**
